# Examples for xxxCookie
remDr <- remoteDr()
remDr %>% go("https://www.google.com/ncr")
remDr %>% getTitle()
remDr %>% getCookie()
remDr %>% getCookie("NID")
remDr %>% addCookie(name = "myCookie", value = "12")
remDr %>% getCookie("myCookie")
remDr %>% deleteCookie("myCookie")
remDr %>% getCookie("myCookie")
remDr %>% getCookie()
remDr %>% deleteAllCookies()
remDr %>% getCookie()

remDr %>% deleteSession()
